/** spec-ref: Mesh_Execution_Compiled_v_1.md §13.2 */
export const REASON_CODES = {
  MALFORMED_COMMAND: "CMD.VALIDATION.KERNEL.MALFORMED_COMMAND",
  EMPTY_TX: "CMD.VALIDATION.KERNEL.EMPTY_TX",
  DUPLICATE_EVENT_ID_IN_TX: "CMD.VALIDATION.KERNEL.DUPLICATE_EVENT_ID_IN_TX",
  INVALID_BASE_REVISION: "CMD.VALIDATION.REVISION.INVALID_BASE_REVISION",
  REVISION_MISMATCH: "CMD.PRECONDITION.REVISION.MISMATCH",
  IDEMPOTENCY_PAYLOAD_MISMATCH: "CMD.CONFLICT.IDEMPOTENCY.PAYLOAD_MISMATCH",
  LOCKED: "CMD.CONFLICT.LOCKED",
  NOT_FOUND_GENERIC: "CMD.NOT_FOUND.GENERIC",
  NOT_FOUND_OR_MASKED: "CMD.NOT_FOUND.SECURITY.INDISTINGUISHABLE",
  EVENTSTORE_WRITE_FAILED: "CMD.INTERNAL.EVENTSTORE.WRITE_FAILED",
  EVENTSTORE_CORRUPT_TX_INDEX: "CMD.INTERNAL.EVENTSTORE.CORRUPT_TX_INDEX"
} as const;

export type ReasonCode = (typeof REASON_CODES)[keyof typeof REASON_CODES];
